"""Environment variable and configuration file management."""

import os
from pathlib import Path
from typing import Dict, Iterable, List

from evaluator.paths import get_home_dir
from dotenv import load_dotenv


def get_user_env_path() -> Path:
    """Store config under oscanner home dir (user-local dotfile)."""
    return get_home_dir() / ".env.local"


def get_project_env_paths(server_file: Path | None = None, cwd: Path | None = None) -> List[Path]:
    """
    Return project env files in load order.

    Priority:
    1) Server-directory `.env.local`
    2) Current working directory `.env.local` (when different)
    """
    paths: List[Path] = []
    seen: set[Path] = set()

    candidates: Iterable[Path] = []
    if server_file is not None:
        candidates = [server_file.resolve().parent / ".env.local"]
    if cwd is not None:
        candidates = [*candidates, cwd.resolve() / ".env.local"]

    for path in candidates:
        resolved = path.resolve()
        if resolved in seen or not resolved.exists():
            continue
        seen.add(resolved)
        paths.append(resolved)
    return paths


def load_runtime_env(server_file: Path | None = None, cwd: Path | None = None) -> List[Path]:
    """
    Load runtime env files in a stable order and return the files that were loaded.
    """
    loaded: List[Path] = []

    for path in get_project_env_paths(server_file=server_file, cwd=cwd):
        # Treat empty inherited env vars as unset so file-backed values can restore
        # them without overriding genuinely non-empty process configuration.
        for key, value in parse_env_file(path).items():
            if value and os.environ.get(key) == "":
                os.environ.pop(key, None)
        load_dotenv(path, override=False)
        loaded.append(path)

    user_env_path = get_user_env_path()
    if user_env_path.exists():
        for key, value in parse_env_file(user_env_path).items():
            if value and os.environ.get(key) == "":
                os.environ.pop(key, None)
        load_dotenv(user_env_path, override=False)
        loaded.append(user_env_path)

    load_dotenv(override=False)
    return loaded


def parse_env_file(path: Path) -> Dict[str, str]:
    """Parse .env file into dictionary."""
    env: Dict[str, str] = {}
    try:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    except FileNotFoundError:
        return {}
    except Exception:
        return env
    return env


def write_env_file(path: Path, env: Dict[str, str]) -> None:
    """Write environment variables to .env file with standard ordering."""
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Generated by oscanner dashboard LLM settings",
        "# - Do NOT commit real keys to git.",
        "",
    ]
    order = [
        "GITEE_TOKEN",
        "GITHUB_TOKEN",
        "OPEN_ROUTER_KEY",
        "OSCANNER_LLM_API_KEY",
        "OSCANNER_LLM_BASE_URL",
        "OSCANNER_LLM_CHAT_COMPLETIONS_URL",
        "OSCANNER_LLM_MODEL",
        "OSCANNER_LLM_FALLBACK_MODELS",
        "OPENAI_API_KEY",
        "OPENAI_BASE_URL",
    ]
    lines: List[str] = []
    lines.extend(header)
    for k in order:
        if k in env and env[k] != "":
            lines.append(f"{k}={env[k]}")
    # keep any other keys stable (avoid losing tokens like GITHUB_TOKEN if user adds here)
    for k in sorted(env.keys()):
        if k in order:
            continue
        if env[k] == "":
            continue
        lines.append(f"{k}={env[k]}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def apply_env_to_process(env: Dict[str, str]) -> None:
    """Update current process env so changes take effect without restart."""
    for k, v in env.items():
        if v is None:
            continue
        if v == "":
            os.environ.pop(k, None)
        else:
            os.environ[k] = v
