"""Environment variable and configuration file management."""

import os
from pathlib import Path
from typing import Dict, List

from evaluator.paths import get_home_dir


def get_user_env_path() -> Path:
    """Store config under oscanner home dir (user-local dotfile)."""
    return get_home_dir() / ".env.local"


def parse_env_file(path: Path) -> Dict[str, str]:
    """Parse .env file into dictionary."""
    env: Dict[str, str] = {}
    try:
        for raw in path.read_text(encoding="utf-8").splitlines():
            line = raw.strip()
            if not line or line.startswith("#") or "=" not in line:
                continue
            k, v = line.split("=", 1)
            env[k.strip()] = v.strip()
    except FileNotFoundError:
        return {}
    except Exception:
        return env
    return env


def write_env_file(path: Path, env: Dict[str, str]) -> None:
    """Write environment variables to .env file with standard ordering."""
    path.parent.mkdir(parents=True, exist_ok=True)
    header = [
        "# Generated by oscanner dashboard LLM settings",
        "# - Do NOT commit real keys to git.",
        "",
    ]
    order = [
        "GITEE_TOKEN",
        "GITHUB_TOKEN",
        "OPEN_ROUTER_KEY",
        "OSCANNER_LLM_API_KEY",
        "OSCANNER_LLM_BASE_URL",
        "OSCANNER_LLM_CHAT_COMPLETIONS_URL",
        "OSCANNER_LLM_MODEL",
        "OSCANNER_LLM_FALLBACK_MODELS",
        "OPENAI_API_KEY",
        "OPENAI_BASE_URL",
    ]
    lines: List[str] = []
    lines.extend(header)
    for k in order:
        if k in env and env[k] != "":
            lines.append(f"{k}={env[k]}")
    # keep any other keys stable (avoid losing tokens like GITHUB_TOKEN if user adds here)
    for k in sorted(env.keys()):
        if k in order:
            continue
        if env[k] == "":
            continue
        lines.append(f"{k}={env[k]}")
    lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def apply_env_to_process(env: Dict[str, str]) -> None:
    """Update current process env so changes take effect without restart."""
    for k, v in env.items():
        if v is None:
            continue
        if v == "":
            os.environ.pop(k, None)
        else:
            os.environ[k] = v
