version: '1.0'
name: pr-pipeline
displayName: PRPipeline
stages:
  - stage:
    name: lint
    displayName: 代码检查
    steps:
      - step: build@python
        name: lint_python
        displayName: Python 代码检查
        pythonVersion: '3.9'
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install uv ruff
          - uv lock
          - uv sync
          - ruff check . || echo "Linting issues found"

      - step: build@nodejs
        name: lint_webapp
        displayName: Webapp 代码检查
        nodeVersion: '20'
        commands:
          - cd webapp
          - npm config set registry https://registry.npmmirror.com
          - npm install
          - npm run lint || echo "Linting issues found"

  - stage:
    name: test
    displayName: 测试
    steps:
      - step: build@python
        name: test_python
        displayName: Python 测试
        pythonVersion: '3.9'
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install uv
          - uv lock
          - uv sync
          - uv run pytest || echo "No tests found, skipping"

  - stage:
    name: build
    displayName: 构建验证
    steps:
      - step: build@python
        name: build_python
        displayName: Python 构建
        pythonVersion: '3.9'
        commands:
          - python3 -m pip install --upgrade pip
          - pip3 config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
          - pip3 install build uv
          - uv lock
          - uv sync
          - python3 -m build

      - step: build@nodejs
        name: build_webapp
        displayName: Webapp 构建
        nodeVersion: '20'
        commands:
          - cd webapp
          - npm config set registry https://registry.npmmirror.com
          - npm install
          - npm run build

triggers:
  pr:
    branches:
      include:
        - master
        - main
